POST http://localhost:8080/api/register HTTP/1.1
content-type: application/json

{
  "email": "jokke34@gmail.com",
  "name": "Joakim Olsen",
  "password": "test123",
  "role": "User",
  "company": "LogiSnap"
}

###
POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "email": "jokke34@gmail.com",
  "password": "test123"
}

###

GET http://localhost:8080/api/public-route HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/api/people/email/lars@gmail.com HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWM4ZTgxZjhhYThmZTJlYWExY2YwNmEiLCJlbWFpbCI6Impva2tlMzRAZ21haWwuY29tIiwibmFtZSI6IkpvYWtpbSBPbHNlbiIsInJvbGUiOiJVc2VyIiwiY29tcGFueSI6IkZhY2Vib29rIiwiZXhwIjoxNjYxMTk5MTQ0LjM3OH0.iMjU40aVcZ8AV65mU_uwQKd33yIZK2-JFDkSoLFw-Zc