POST http://localhost:8080/api/register HTTP/1.1
content-type: application/json

{
  "email": "jokke34@gmail.com",
  "name": "Joakim Olsen",
  "password": "test123",
  "role": "User",
  "company": "LogiSnap"
}

###
POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "email": "jokke34@gmail.com",
  "password": "test123"
}

###

GET http://localhost:8080/api/public-route HTTP/1.1
content-type: application/json

